// <auto-generated />
using System;
using CrickerScorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrickerScorer.Migrations
{
    [DbContext(typeof(CricketDbContext))]
    partial class CricketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrickerScorer.Models.BallAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BallType")
                        .HasColumnType("integer");

                    b.Property<string>("ColorClass")
                        .HasColumnType("text");

                    b.Property<string>("Commentary")
                        .HasColumnType("text");

                    b.Property<int>("DeliveryNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraRuns")
                        .HasColumnType("integer");

                    b.Property<int?>("LegalBallNumber")
                        .HasColumnType("integer");

                    b.Property<int>("OverthrowRuns")
                        .HasColumnType("integer");

                    b.Property<int>("Runs")
                        .HasColumnType("integer");

                    b.Property<string>("ShortCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wicket")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BallActions");
                });
#pragma warning restore 612, 618
        }
    }
}
